name: conda CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-conda:
    if: contains(github.event.pull_request.title, '[release]')
    runs-on: self-hosted
    container:
      image: lmsysorg/sglang:v0.5.0rc0-cu126
      options: --gpus all --ipc=host --shm-size=16g --ulimit memlock=-1 --ulimit stack=67108864 --memory=0 --memory-swap=0 -v /mnt/nvme0n1/models:/root/models -v /mnt/nvme0n1/datasets:/root/datasets

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Construct Conda
        run: |
          echo "📦 Installing slime..."
          cd $GITHUB_WORKSPACE
          echo "Current directory: $(pwd)"

          mkdir -p /root/
          BASE_DIR=/root bash build_conda.sh
        shell: bash

      - name: Download model and dataset
        run: |
          echo "🔗 Downloading up model and dataset..."
          
          # Create cache directories if they don't exist
          mkdir -p /root/models /root/datasets
          
          echo "Downloading Qwen3-30B-A3B..."
          hf download Qwen/Qwen3-30B-A3B --local-dir /root/models/Qwen3-30B-A3B
          hf download Qwen/Qwen3-30B-A3B-FP8 --local-dir /root/models/Qwen3-30B-A3B-FP8
          
          hf download --repo-type dataset zhuzilin/dapo-math-17k --local-dir /root/datasets/dapo-math-17k

          hf download --repo-type dataset zhuzilin/aime-2024 --local-dir /root/datasets/aime-2024
        shell: bash

      - name: Convert checkpoint
        run: |
          echo "🔄 Converting model checkpoint..."
          cd $GITHUB_WORKSPACE
          echo "Current directory: $(pwd)"

          source ~/.bashrc
          micromamba activate slime
          export CUDA_HOME="$CONDA_PREFIX"

          source scripts/models/qwen3-30B-A3B.sh
          PYTHONPATH=/root/Megatron-LM torchrun --nproc-per-node 8 tools/convert_hf_to_torch_dist.py \
            ${MODEL_ARGS[@]} \
            --hf-checkpoint /root/models/Qwen3-30B-A3B \
            --save /root/Qwen3-30B-A3B_torch_dist
        shell: bash

      - name: Run tests
        run: |
          echo "🧪 Running tests..."
          cd $GITHUB_WORKSPACE
          echo "Current directory: $(pwd)"

          source ~/.bashrc
          micromamba activate slime
          export CUDA_HOME="$CONDA_PREFIX"

          bash tests/test_qwen3-30B-A3B.sh
        shell: bash
          
      - name: Cleanup
        if: always()
        run: |
          echo "🧹 Cleaning up..."
          pkill -9 ray || true
          ray stop --force || true
          pkill -9 python || true
        shell: bash
