name: PR Test

on:
  # Do not run CI on push to reduce CI time
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test:
    # TODO may use run-ci label etc
    if: github.event.pull_request.draft == false
    runs-on: self-hosted
    container:
      image: slimerl/slime:latest
      options: >
        --gpus all
        --ipc=host
        --shm-size=16g
        --ulimit memlock=-1
        --ulimit stack=67108864
        --memory=0
        --memory-swap=0
        -v /mnt/nvme0n1/slime_ci:/data/slime_ci
        -v /mnt/nvme0n1/models:/root/models
        -v /mnt/nvme0n1/datasets:/root/datasets
    strategy:
      fail-fast: false
      matrix:
        info:
          - {test_file: test_quick_start_glm4_9B.py}
          - {test_file: test_qwen3_30B_A3B.py}
          # TODO use deterministic kernel
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    env:
      GITHUB_COMMIT_NAME: ${{ github.sha }}_${{ github.event.pull_request.number || 'non-pr' }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install
        shell: bash
        run: cd $GITHUB_WORKSPACE && pip install -e .

      - name: Execute
        shell: bash
        run: python tests/${{ matrix.info.test_file }}
